### PR TITLE
Adding corona data

### LINKED ISSUE #15: Add local coronavirus data section - using python
As a user I would like to see my local coronavirus data as published by [gov.uk](https://coronavirus.data.gov.uk/developers-guide#latestby-example)

**Describe the solution you'd like**

- Add a section to the html (above the news)
- create a new script ``coronavirus.py``.
- using the python examples from the above linked site
- ideally post the last 3 days worth of cases and deaths as bulleted list
- use GitHub secrets for the location and pass this in through the build

### PR DESCRIPTION
**Pull request by malathit**
Closes #15

### CODE REVIEW

**Comment by MatBenfield** [comment]
Many thanks for this. :-)

**Comment by malathit** [comment]
This is still in draft. I had some questions mentioned in the issue #15. I can mark this PR to ready for review by tomorrow

**Comment by malathit** [comment]
> Many thanks for this. I would like more localised data i.e town or city level. And being able to pass the location in through Github-secrets. Could this be added?

Yes it is feasible. Right now the code just uses this filter
`areaType=nation;areaName=england`

**Comment by malathit** [comment]
I just saw that the API let us query using nation/region/local authority. I am not sure if city/town comes under the local authority. If yes, I can make the changes

**Comment by MatBenfield** [comment]
Local authority would be close enough to provide the value and information I am looking for, if you could implement that, it would useful thank you. This would mean updating the python script to pull in a GitHub secret (other scripts have examples of this) 

thanks

**Comment by MatBenfield** [comment]
Many thanks for this, I am happy to accept the PR.

**Pull request merged**
